plugins {
    id 'eclipse'
    id 'idea'
    id 'com.modrinth.minotaur' version '2.+'
    id 'net.neoforged.gradle.userdev' version '7.0.+'
}

repositories {
    maven {
        url "https://maven.su5ed.dev/releases"
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven { url = 'https://maven.fabricmc.net' }
    maven {
        name "CaffeineMC"
        url "https://maven.caffeinemc.net/releases" // or /snapshots
    }
}

group= "team.creative" + project.mod_id

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

java.sourceSets.create("api") {
    
    java {
        srcDir("src/api/java")
    }
    compileClasspath += sourceSets.main.compileClasspath
    runtimeClasspath += sourceSets.main.runtimeClasspath
}

sourceSets.main.compileClasspath += sourceSets.api.output
sourceSets.main.runtimeClasspath += sourceSets.api.output

project.evaluationDependsOn(":CreativeCore")

runs {  
    configureEach {
        workingDirectory project.file('run')
        systemProperty 'forge.logging.console.level', 'debug'
    }
    
    client {
    }
    
    server {
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${forge_version}"
    
    implementation project(':CreativeCore')
    
    implementation("net.caffeinemc:sodium-neoforge-mod:0.8.12-alpha.4+mc1.21.1")
}

modDependencies = [
    [ modId: "creativecore", type: "required", ordering: "NONE", side: "BOTH", versionRange: "[" + creativecore_version + ",)" ]
]
modMixins = [ "littletiles.mixins.json" ]
modProperties = [
    '',
    '["lithium:options"]',
    '    "mixin.shapes.specialized_shapes" = false',
    '    "mixin.entity.collisions" = false'
]
modImplemented = [
    [ name: "maven.modrinth:iris:t3ruzodq", disabled: true ],
    [ name: "curse.maven:theoneprobe-245211:5502323", disabled: true ],
    [ name: "net.fabricmc:fabric-loader:${project.fabric_version}", disabled: true ],
    [ name: "org.sinytra.forgified-fabric-api:fabric-api-base:0.4.42+d1308ded19" , disabled: true ],
    [ name: "org.sinytra.forgified-fabric-api:fabric-renderer-api-v1:3.4.0+acb05a3919", disabled: true ],
    [ name: "org.sinytra.forgified-fabric-api:fabric-rendering-data-attachment-v1:0.3.48+73761d2e19", disabled: true ],
    [ name: "org.sinytra.forgified-fabric-api:fabric-block-view-api-v2:1.0.10+9afaaf8c19", disabled: true ],
]
