modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/CreativeMD/LittleTiles/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="littletiles"
    logoFile="littletiles.png"
    version="1.6.0-pre087"
    displayName="LittleTiles"
    displayURL="https://modrinth.com/mod/littletiles"
    authors="CreativeMD, N247S"
    description='''#BuildItYourself'''

[[dependencies.littletiles]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.littletiles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.littletiles]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="2.11.19"

