modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/LittleTiles/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="littletiles"
    logoFile="littletiles.png"
    version="1.6.0-pre128"
    displayName="LittleTiles"
    displayURL="https://modrinth.com/mod/littletiles"
    authors="CreativeMD, N247S"
    description='''#BuildItYourself'''

[[dependencies.littletiles]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.littletiles]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.littletiles]]
   modId="creativecore"
   type="required"
   ordering="NONE"
   side="BOTH"
   versionRange="[2.12.15,)"

[[mixins]]
   config="littletiles.mixins.json"

